---
deployment:
  tasks:
    - export DEPLOYPATH=/home/alineamu/public_html/
    - /bin/cp index.php $DEPLOYPATH
    - /bin/cp googled9ba2263786741f0.html $DEPLOYPATH
    - /bin/cp common_variables.php $DEPLOYPATH
    - /bin/cp -R datas $DEPLOYPATH
    - /bin/cp -R views $DEPLOYPATH
    - /bin/mkdir $DEPLOYPATH/assets
    - /bin/cp -R assets/audio $DEPLOYPATH/assets
    - /bin/cp -R assets/img $DEPLOYPATH/assets
    - /bin/cp -R assets/js $DEPLOYPATH/assets
    - /bin/mkdir $DEPLOYPATH/assets/css
    - /bin/cp assets/css/main_style.css $DEPLOYPATH/assets/css